"""Reusable building blocks for the notebooks in this repo."""

from .data_loader import (
    DatasetMeta,
    LazyDataset,
    build_lazy_grid,
    discover_datasets,
    iter_windowed_bars,
    load_all,
    load_all_lazy,
    load_csv,
    resample_ohlc,
)
from .strategy import (
    SMACrossoverStrategy,
    StrategyParams,
    RSIMeanReversionStrategy,
    RSIMeanReversionParams,
    KeltnerReversionStrategy,
    KeltnerReversionParams,
    EMARibbonStrategy,
    EMARibbonParams,
    DonchianBreakoutStrategy,
    DonchianBreakoutParams,
    MACDHistogramStrategy,
    MACDHistogramParams,
    BBSqueezeStrategy,
    BBSqueezeParams,
)
from .backtest import Backtester, BacktestResult, Trade
from .metrics import compute_metrics, metrics_table
from .dashboard import (
    plot_backtest_dashboard,
    plot_wfo_dashboard,
    plot_robustness_dashboard,
)
from .wfo import walk_forward, WFOResult, default_score
from .robustness import (
    monte_carlo_trades,
    monte_carlo_summary,
    block_bootstrap_trades,
    subperiod_analysis,
    parameter_sensitivity,
)
from .portfolio import correlation_weights, weighted_portfolio
from .parallel import cpu_count, parallel_map, resolve_n_jobs
from .runner import (
    GridSpec,
    reshape_grid_results,
    run_backtest_grid,
    run_backtests_with_params,
    run_wfo_grid,
)

__all__ = [
    "DatasetMeta",
    "LazyDataset",
    "build_lazy_grid",
    "discover_datasets",
    "iter_windowed_bars",
    "load_all",
    "load_all_lazy",
    "load_csv",
    "resample_ohlc",
    "SMACrossoverStrategy",
    "StrategyParams",
    "RSIMeanReversionStrategy",
    "RSIMeanReversionParams",
    "KeltnerReversionStrategy",
    "KeltnerReversionParams",
    "EMARibbonStrategy",
    "EMARibbonParams",
    "DonchianBreakoutStrategy",
    "DonchianBreakoutParams",
    "MACDHistogramStrategy",
    "MACDHistogramParams",
    "BBSqueezeStrategy",
    "BBSqueezeParams",
    "Backtester",
    "BacktestResult",
    "Trade",
    "compute_metrics",
    "metrics_table",
    "plot_backtest_dashboard",
    "plot_wfo_dashboard",
    "plot_robustness_dashboard",
    "walk_forward",
    "WFOResult",
    "default_score",
    "monte_carlo_trades",
    "monte_carlo_summary",
    "block_bootstrap_trades",
    "subperiod_analysis",
    "parameter_sensitivity",
    "correlation_weights",
    "weighted_portfolio",
    "cpu_count",
    "parallel_map",
    "resolve_n_jobs",
    "GridSpec",
    "reshape_grid_results",
    "run_backtest_grid",
    "run_backtests_with_params",
    "run_wfo_grid",
]
